//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.237
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Препараты_и_фирмы_их_поставляющие {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Препараты_и_фирмы_их_поставляющие() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project1.Препараты_и_фирмы_их_поставляющие", typeof(Препараты_и_фирмы_их_поставляющие).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorAddNewItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorAddNewItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorDeleteItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorDeleteItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveFirstItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveLastItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMoveNextItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bindingNavigatorMovePreviousItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static bool nПрепаратаLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("nПрепаратаLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Point selResultBindingNavigator_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("selResultBindingNavigator.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selResultBindingNavigatorSaveItem_Image {
            get {
                object obj = ResourceManager.GetObject("selResultBindingNavigatorSaveItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Point selResultBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("selResultBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static bool адресLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("адресLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool количество_штукLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("количество_штукLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool название_препаратаLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("название_препаратаLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool название_фирмыLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("название_фирмыLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool производительLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("производительLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool срок_храненияLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("срок_храненияLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool тип_препаратаLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("тип_препаратаLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool ценаLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ценаLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
