//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.237
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Фирмы_табл {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Фирмы_табл() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project1.Фирмы_табл", typeof(Фирмы_табл).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorAddNewItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorAddNewItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorDeleteItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorDeleteItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorMoveFirstItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorMoveLastItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorMoveNextItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bindingNavigatorMovePreviousItem {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static bool label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool адресLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("адресLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool банкLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("банкLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool бИКLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("бИКLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool идентификационный_номерLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("идентификационный_номерLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool название_фирмыLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("название_фирмыLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point прайс_ценsBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("прайс_ценsBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static bool расчетный_счетLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("расчетный_счетLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool сайтLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("сайтLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool телефонLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("телефонLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point фирмыBindingNavigator_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("фирмыBindingNavigator.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Bitmap фирмыBindingNavigatorSaveItem_Image {
            get {
                object obj = ResourceManager.GetObject("фирмыBindingNavigatorSaveItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Point фирмыBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("фирмыBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static bool шифр_фирмыLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("шифр_фирмыLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
